# Generated by Django 5.0.1 on 2024-01-20 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_name', models.CharField(max_length=30)),
                ('res_type', models.CharField(choices=[('Fast food', 'Fast food'), ('Cafeteria', 'Cafeteria'), ('Bakery', 'Bakery'), ('Family Style', 'Family Style')], max_length=20)),
                ('res_user', models.CharField(max_length=30)),
                ('res_pass', models.CharField(max_length=30)),
                ('res_cpass', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.CharField(max_length=30)),
                ('room_type', models.CharField(choices=[('Deluxe Room', 'Deluxe Room'), ('Single room', 'Single room'), ('King room', 'King room')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_name', models.CharField(max_length=30)),
                ('st_address', models.CharField(max_length=30)),
                ('st_no', models.CharField(max_length=30)),
                ('st_position', models.CharField(choices=[('Housekeeping', 'Housekeeping'), ('Security', 'Security'), ('Supervisor', 'Supervisor'), ('Manager', 'Manager'), ('Human Resources', 'Human Resources')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=30)),
                ('food_description', models.CharField(max_length=30)),
                ('food_price', models.IntegerField()),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.restaurants')),
            ],
        ),
    ]
