# Generated by Django 5.0.1 on 2024-01-22 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='st_address',
            new_name='Staff_address',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='st_name',
            new_name='Staff_name',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='st_no',
            new_name='Staff_no',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='st_position',
            new_name='Staff_position',
        ),
    ]
